/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://dblxirthmvg25gixz2zsyktxde.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z447by2265adtj5wspy3wliuaq",
    "aws_cognito_identity_pool_id": "us-west-2:ec31f774-0742-4c2c-a026-ad59cff2bf25",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_1r0vd66Ba",
    "aws_user_pools_web_client_id": "52ss7695o6fhklnvploa2rljk9",
    "oauth": {},
    "aws_user_files_s3_bucket": "image-bucket160054-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
